# Generated by Django 4.1.3 on 2022-11-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sub_category',
            field=models.CharField(default='', max_length=100),
        ),
    ]
