# Generated by Django 4.1.3 on 2022-11-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon_disc',
            field=models.BooleanField(default=False),
        ),
    ]
