# Generated by Django 4.1.3 on 2022-11-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_cart_coupon_disc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='coupon_disc',
        ),
    ]
