# Generated by Django 4.1.3 on 2022-11-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_cart_coupon_disc'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_cost',
            field=models.CharField(default='Free', max_length=100),
        ),
    ]
