# Generated by Django 4.1.3 on 2022-11-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_cart_discount_cart_shipping_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='shipping_cost',
        ),
    ]
