# Generated by Django 4.1.3 on 2022-11-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_remove_cart_discount_remove_cart_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
