# Generated by Django 4.1.3 on 2022-11-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_disc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
