# Generated by Django 4.1.3 on 2022-12-24 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_price',
            new_name='grand_total',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='sub_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_qty',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
